import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from db import get_profile


def send_welcome_email():
      """Send a welcome email to the user after they save their profile."""
      profile = get_profile()
      if not profile:
                print("No profile found, skipping welcome email.")
                return False

      email = profile.get("email", "")
      if not email:
                print("No email in profile, skipping welcome email.")
                return False

      gmail_user = os.getenv("GMAIL_USER", "")
      gmail_pass = os.getenv("GMAIL_APP_PASSWORD", "")
      if not gmail_user or not gmail_pass:
                print("Gmail credentials not set, skipping welcome email.")
                return False

      first_name = profile.get("name", "there").split()[0] if profile.get("name") else "there"
      titles = profile.get("titles", [])
      titles_str = ", ".join(titles) if titles else "your target roles"
      location = profile.get("location", "Remote")
      min_salary = profile.get("min_salary", 0)

    html = f"""
        <html>
            <body style="margin:0;padding:0;font-family:Arial,Helvetica,sans-serif;background:#f4f4f4;">
                  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f4f4;padding:20px 0;">
                          <tr>
                                    <td align="center">
                                                <table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:8px;overflow:hidden;">
                                                              <!-- Header -->
                                                                            <tr>
                                                                                            <td style="background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);padding:30px 40px;text-align:center;">
                                                                                                              <h1 style="color:#ffffff;margin:0;font-size:26px;">Welcome to Job Agent!</h1>
                                                                                                                                <p style="color:#e0d4f7;margin:8px 0 0;font-size:14px;">Your AI-powered job search assistant</p>
                                                                                                                                                </td>
                                                                                                                                                              </tr>
                                                                                                                                                              
                                                                                                                                                                            <!-- Greeting -->
                                                                                                                                                                                          <tr>
                                                                                                                                                                                                          <td style="padding:30px 40px 10px;">
                                                                                                                                                                                                                            <h2 style="color:#333;margin:0 0 10px;font-size:20px;">Hey {first_name}!</h2>
                                                                                                                                                                                                                                              <p style="color:#555;font-size:15px;line-height:1.6;">
                                                                                                                                                                                                                                                                  Thanks for setting up your profile. Your Job Agent is now ready to help you
                                                                                                                                                                                                                                                                                      find the perfect role. Here is a quick guide to get the best results.
                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                        </td>
                                                                                                                                                                                                                                                                                                                                      </tr>
                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                    <!-- How It Works -->
                                                                                                                                                                                                                                                                                                                                                                  <tr>
                                                                                                                                                                                                                                                                                                                                                                                  <td style="padding:10px 40px;">
                                                                                                                                                                                                                                                                                                                                                                                                    <h3 style="color:#667eea;margin:0 0 8px;font-size:17px;">How It Works</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                      <p style="color:#555;font-size:14px;line-height:1.6;">
                                                                                                                                                                                                                                                                                                                                                                                                                                          Job Agent searches <strong>5 job boards</strong> (Adzuna, The Muse, RemoteOK,
                                                                                                                                                                                                                                                                                                                                                                                                                                                              JSearch, and Google Jobs) for positions matching your preferences. Then our
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <strong>AI grading engine</strong> scores each job based on how well it fits
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      your skills, experience, and dealbreakers. You get only the best matches.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <!-- Tips -->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td style="padding:10px 40px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3 style="color:#667eea;margin:0 0 8px;font-size:17px;">Tips for Best Results</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <table width="100%" cellpadding="8" cellspacing="0" style="font-size:14px;color:#555;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <td style="vertical-align:top;width:30px;color:#667eea;font-weight:bold;">1.</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <td><strong>Be specific with job titles</strong> &mdash; Instead of just "Developer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              try "Python Developer" or "Junior Software Engineer". More specific titles
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      help narrow down the best matches.</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td style="vertical-align:top;width:30px;color:#667eea;font-weight:bold;">2.</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <td><strong>Add your resume</strong> &mdash; Paste your resume text or upload a file
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  so the AI can match your actual skills and experience to each job posting.</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <td style="vertical-align:top;width:30px;color:#667eea;font-weight:bold;">3.</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <td><strong>Set dealbreakers wisely</strong> &mdash; If something is truly a must-have
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              (like remote work or a minimum salary), mark it as a dealbreaker. Jobs that
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fail dealbreakers are filtered out.</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td style="vertical-align:top;width:30px;color:#667eea;font-weight:bold;">4.</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <td><strong>Use Scan Jobs Now</strong> &mdash; Hit the instant scan button on your
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  dashboard to run a search anytime. You will also get automatic daily emails
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          with fresh matches.</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <!-- Example Job List -->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <td style="padding:10px 40px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3 style="color:#667eea;margin:0 0 8px;font-size:17px;">What Your Daily Email Looks Like</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p style="color:#555;font-size:14px;line-height:1.5;margin:0 0 12px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Here is an example of the kind of matches you will receive:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <table width="100%" cellpadding="10" cellspacing="0"
                         style="border:1px solid #e0e0e0;border-radius:6px;font-size:13px;">
                                             <tr style="background:#f8f7ff;">
                                                                   <td style="border-bottom:1px solid #e0e0e0;">
                                                                                           <strong style="color:#333;">Junior Python Developer</strong><br>
                                                                                                                   <span style="color:#888;">Acme Corp &mdash; Remote, US</span><br>
                                                                                                                                           <span style="color:#667eea;font-weight:bold;">AI Grade: STRATEGIC FIT</span>
                                                                                                                                                                   <span style="color:#888;"> | </span>
                                                                                                                                                                                           <span style="color:#28a745;">Salary: $65,000 - $80,000</span>
                                                                                                                                                                                                                 </td>
                                                                                                                                                                                                                                     </tr>
                                                                                                                                                                                                                                                         <tr>
                                                                                                                                                                                                                                                                               <td style="border-bottom:1px solid #e0e0e0;">
                                                                                                                                                                                                                                                                                                       <strong style="color:#333;">Entry Level Software Engineer (Python)</strong><br>
                                                                                                                                                                                                                                                                                                                               <span style="color:#888;">TechStart Inc &mdash; Remote, US</span><br>
                                                                                                                                                                                                                                                                                                                                                       <span style="color:#667eea;font-weight:bold;">AI Grade: STRONG MATCH</span>
                                                                                                                                                                                                                                                                                                                                                                               <span style="color:#888;"> | </span>
                                                                                                                                                                                                                                                                                                                                                                                                       <span style="color:#28a745;">Salary: $70,000 - $90,000</span>
                                                                                                                                                                                                                                                                                                                                                                                                                             </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                 </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <tr style="background:#f8f7ff;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <strong style="color:#333;">Python Automation Engineer</strong><br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <span style="color:#888;">DataFlow LLC &mdash; Remote, US</span><br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <span style="color:#667eea;font-weight:bold;">AI Grade: PROFESSIONAL FIT</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <span style="color:#888;"> | </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <span style="color:#28a745;">Salary: $60,000 - $75,000</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <p style="color:#999;font-size:12px;margin:8px 0 0;text-align:center;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     (These are examples. Your actual matches will be based on real job listings.)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <!-- Current Settings -->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <td style="padding:20px 40px;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <h3 style="color:#667eea;margin:0 0 8px;font-size:17px;">Your Current Settings</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <table width="100%" cellpadding="6" cellspacing="0"
                         style="border:1px solid #e0e0e0;border-radius:6px;font-size:14px;">
                                             <tr style="background:#f8f7ff;">
                                                                   <td style="color:#888;width:140px;border-bottom:1px solid #e0e0e0;">Job Titles</td>
                                                                                         <td style="color:#333;border-bottom:1px solid #e0e0e0;">{titles_str}</td>
                                                                                                             </tr>
                                                                                                                                 <tr>
                                                                                                                                                       <td style="color:#888;border-bottom:1px solid #e0e0e0;">Location</td>
                                                                                                                                                                             <td style="color:#333;border-bottom:1px solid #e0e0e0;">{location}</td>
                                                                                                                                                                                                 </tr>
                                                                                                                                                                                                                     <tr style="background:#f8f7ff;">
                                                                                                                                                                                                                                           <td style="color:#888;">Min Salary</td>
                                                                                                                                                                                                                                                                 <td style="color:#333;">${min_salary:,}</td>
                                                                                                                                                                                                                                                                                     </tr>
                                                                                                                                                                                                                                                                                                       </table>
                                                                                                                                                                                                                                                                                                                       </td>
                                                                                                                                                                                                                                                                                                                                     </tr>
                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                   <!-- Footer -->
                                                                                                                                                                                                                                                                                                                                                                 <tr>
                                                                                                                                                                                                                                                                                                                                                                                 <td style="background:#f8f7ff;padding:20px 40px;text-align:center;border-top:1px solid #e0e0e0;">
                                                                                                                                                                                                                                                                                                                                                                                                   <p style="color:#999;font-size:12px;margin:0;">
                                                                                                                                                                                                                                                                                                                                                                                                                       Job Agent &mdash; Built with Streamlit, Supabase, and Google Gemini AI
                                                                                                                                                                                                                                                                                                                                                                                                                                         </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                         </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       """

    msg = MIMEMultipart("alternative")
    msg["Subject"] = "Welcome to Job Agent - Your AI Job Search Starts Now!"
    msg["From"] = gmail_user
    msg["To"] = email
    msg.attach(MIMEText(html, "html"))

    try:
              with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
                            server.login(gmail_user, gmail_pass)
                            server.sendmail(gmail_user, email, msg.as_string())
                        print(f"Welcome email sent to {email}")
        return True
except Exception as e:
        print(f"Failed to send welcome email: {e}")
        return False
